### ISSUE TITLE
set_val and set_val_old ends with error

### ISSUE THREAD

**Issue by schneemaier** [xandr2/blynkapi#1]
Using set_val method results in 404 error: HTTPError code = 404 HTTPError msg = Not Found
set_val_old method results in 500 error

sample code:
roomHeatingStatus = Blynk(authToken, pin = "V3")

.....
roomHeatingStatus.set_val(str(255))

Directly writing to pin in browser works fine: http://blynk-cloud.com/shs...fghs..fghs..fgh/update/V3?value=255

Also on and off methods, get_val method works fine

**Comment by xandr2** [comment]
Hi! Sorry, I've just seen your request. On [README.md](https://github.com/xandr2/blynkapi/blob/master/README.md) you can see a definition of method `set_val` you have to pass to function a list with values (because it can be more than one).
Try it:
`roomHeatingStatus.set_val(["255"])`

**Comment by schneemaier** [comment]
Thanks!
